# Generated by Django 4.2.3 on 2023-07-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
